services:
  - type: web
    name: kakomon-database
    runtime: ruby
    # Bundler を先に 2.7.2 で入れてから、そのバージョンで実行
    buildCommand: gem install bundler -v 2.7.2 && bundle _2.7.2_ install && bundle _2.7.2_ exec rake db:migrate
    startCommand: bundle _2.7.2_ exec ruby app.rb -o 0.0.0.0 -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kakomon-db
          property: connectionString
      - key: "dxtcmrp4l"
        sync: false
      - key: "846387163656961"
        sync: false
      - key: "N6YrZHJQZud91O4ekrsw6HJcQuE"
        sync: false

databases:
  - name: kakomon-db
    databaseName: kakomon_database
    user: kakomon_user
