# config/database.yml
default_env: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: s_todo

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # RenderのPostgresの接続URL
  pool: 5
